export enum ResponseMessage {
    ALREADY_USER = 'ALREADY_USER',
    AUTH_FAILED = 'AUTH_FAILED',
    CORRECT_SESSION_CHECK = 'CORRECT_SESSION_CHECK',
    ERROR_DURING_SESSION_CHECK = 'ERROR_DURING_SESSION_CHECK',
  }